name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build VitePress site
        run: npm run docs:build

      - name: List build output
        run: ls -la .vitepress/dist

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git clone --depth=1 https://github.com/${{ github.repository }} gh-pages
          cd gh-pages
          git checkout -b gh-pages || git checkout gh-pages
          rsync -av --delete ../.vitepress/dist/ .
          echo "glicol.js.org" > CNAME  # Add CNAME file
          git add --all
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
