name: CI

# Controls when the workflow will run
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build VitePress site
        run: npm run docs:build

      - name: List build output
        run: ls -la .vitepress/dist

      - name: Ensure gh-pages branch exists
        run: |
          if git show-ref --verify --quiet refs/heads/gh-pages; then
            echo "Branch gh-pages already exists."
          else
            echo "Creating gh-pages branch."
            git checkout --orphan gh-pages
            git rm -rf .
            touch README.md
            git add README.md
            git commit -m "Initial commit"
            git push origin gh-pages
            git checkout main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git clone --depth=1 --branch=gh-pages https://github.com/${{ github.repository }} gh-pages
          rsync -av --delete .vitepress/dist/ gh-pages/
          echo "glicol.js.org" > gh-pages/CNAME  # Add CNAME file
          cd gh-pages
          git add --all
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
